"""update typo in user

Revision ID: e37db52ed358
Revises: 3cba7b887199
Create Date: 2021-04-09 10:27:46.474820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37db52ed358'
down_revision = '3cba7b887199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_digest', sa.String(length=255), nullable=False))
    op.drop_column('users', 'pasword_digest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pasword_digest', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_digest')
    # ### end Alembic commands ###
